export const listCategories = JSON.parse(`
[{
    "id": 1,
    "name": "TRÁI CÂY",
    "image": "https://i.imgur.com/2Ifh9Z3.jpg"
  }, {
    "id": 2,
    "name": "RAU SẠCH",
    "image": "https://i.imgur.com/FrkDhTs.jpg"
  }, {
    "id": 3,
    "name": "RAU CỦ",
    "image": "https://i.imgur.com/VFRfN5a.jpg "
  }, {
    "id": 4,
    "name": "LƯƠNG THỰC",
    "image": "https://i.imgur.com/7EzbIhR.jpg"
  }, {
    "id": 11,
    "name": "NƯỚC ÉP",
    "image": "https://i.imgur.com/IE8wAyI.jpg"
  }, {
    "id": 5,
    "name": "THỊT HỮU CƠ",
    "image": "https://i.imgur.com/QmlehLp.jpg"
  }, {
    "id": 6,
    "name": "CÁC LOẠI CÁ",
    "image": "https://i.imgur.com/O2NGeZv.jpg"
  }, {
    "id": 7,
    "name": "SỮA",
    "image": "https://i.imgur.com/z60ZZ3I.jpg"
  }, {
    "id": 8,
    "name": "NGŨ CỐC",
    "image": "https://i.imgur.com/wwUQWXn.jpg"
  }, {
    "id": 9,
    "name": "GẠO",
    "image": "https://i.imgur.com/NGdcCJy.jpg"
  }, {
    "id": 10,
    "name": "QUÀ TẶNG",
    "image": "https://i.imgur.com/O2NGeZv.jpg"
  }]
`);

export const allProducts = JSON.parse(
  `
  [{"id":1,"name":"Seabream Whole Farmed","description":"Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.","category_id":6,"image":"https://picsum.photos/160/161","price":165000,"content":"Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.","unit":"mattis"},
{"id":2,"name":"Snapple Lemon Tea","description":"Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.","category_id":7,"image":"https://picsum.photos/115/116","price":101000,"content":"Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.","unit":"fermentum"},
{"id":3,"name":"Cocktail Napkin Blue","description":"Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.","category_id":5,"image":"https://picsum.photos/132/133","price":61000,"content":"Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.","unit":"tempus"},
{"id":4,"name":"Sauce - Cranberry","description":"Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.","category_id":9,"image":"https://picsum.photos/154/155","price":172000,"content":"Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.","unit":"magnis"},
{"id":5,"name":"Soup - Campbells - Chicken Noodle","description":"Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.","category_id":6,"image":"https://picsum.photos/139/140","price":50000,"content":"Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.","unit":"sapien"},
{"id":6,"name":"Steam Pan Full Lid","description":"Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.","category_id":1,"image":"https://picsum.photos/121/122","price":43000,"content":"Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.","unit":"non"},
{"id":7,"name":"Juice - Grapefruit, 341 Ml","description":"Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.","category_id":2,"image":"https://picsum.photos/186/187","price":19000,"content":"Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.","unit":"ut"},
{"id":8,"name":"Foam Cup 6 Oz","description":"Sed ante. Vivamus tortor. Duis mattis egestas metus.","category_id":1,"image":"https://picsum.photos/260/261","price":179000,"content":"Phasellus in felis. Donec semper sapien a libero. Nam dui.","unit":"erat"},
{"id":9,"name":"Beef - Tongue, Cooked","description":"Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.","category_id":5,"image":"https://picsum.photos/467/468","price":184000,"content":"Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.","unit":"dignissim"},
{"id":10,"name":"Flour - Buckwheat, Dark","description":"Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.","category_id":6,"image":"https://picsum.photos/251/252","price":115000,"content":"Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.","unit":"in"},
{"id":11,"name":"Appetizer - Crab And Brie","description":"Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.","category_id":2,"image":"https://picsum.photos/260/261","price":106000,"content":"In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.","unit":"at"},
{"id":12,"name":"Beer - Guiness","description":"In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.","category_id":6,"image":"https://picsum.photos/292/293","price":105000,"content":"Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.","unit":"vestibulum"},
{"id":13,"name":"Beef - Top Butt Aaa","description":"Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.","category_id":10,"image":"https://picsum.photos/438/439","price":146000,"content":"Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.","unit":"nisi"},
{"id":14,"name":"Wine - Chateau Bonnet","description":"Sed ante. Vivamus tortor. Duis mattis egestas metus.","category_id":9,"image":"https://picsum.photos/490/491","price":90000,"content":"Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.","unit":"neque"},
{"id":15,"name":"Vinegar - Red Wine","description":"Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.","category_id":7,"image":"https://picsum.photos/148/149","price":79000,"content":"Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.","unit":"ac"},
{"id":16,"name":"Pork - Ham Hocks - Smoked","description":"Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.","category_id":6,"image":"https://picsum.photos/370/371","price":184000,"content":"Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.","unit":"sapien"},
{"id":17,"name":"Artichokes - Jerusalem","description":"Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.","category_id":6,"image":"https://picsum.photos/151/152","price":41000,"content":"Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.","unit":"porttitor"},
{"id":18,"name":"Coffee Cup 16oz Foam","description":"Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.","category_id":4,"image":"https://picsum.photos/115/116","price":53000,"content":"Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.","unit":"vestibulum"},
{"id":19,"name":"Towel - Roll White","description":"Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.","category_id":6,"image":"https://picsum.photos/281/282","price":128000,"content":"In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.","unit":"convallis"},
{"id":20,"name":"Lychee","description":"Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.","category_id":1,"image":"https://picsum.photos/332/333","price":51000,"content":"Phasellus in felis. Donec semper sapien a libero. Nam dui.","unit":"pede"},
{"id":21,"name":"Wine - Carmenere Casillero Del","description":"Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.","category_id":10,"image":"https://picsum.photos/422/423","price":70000,"content":"Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.","unit":"mauris"},
{"id":22,"name":"Tea - Lemon Scented","description":"Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.","category_id":4,"image":"https://picsum.photos/395/396","price":49000,"content":"Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.","unit":"sollicitudin"},
{"id":23,"name":"Cheese Cloth No 100","description":"Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.","category_id":7,"image":"https://picsum.photos/357/358","price":98000,"content":"Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.","unit":"sapien"},
{"id":24,"name":"Muffin Puck Ww Carrot","description":"Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.","category_id":3,"image":"https://picsum.photos/299/300","price":181000,"content":"Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.","unit":"lobortis"},
{"id":25,"name":"Fenngreek Seed","description":"Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.","category_id":10,"image":"https://picsum.photos/440/441","price":54000,"content":"Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.","unit":"tortor"},
{"id":26,"name":"Mushroom - Porcini Frozen","description":"Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.","category_id":10,"image":"https://picsum.photos/286/287","price":153000,"content":"Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.","unit":"rhoncus"},
{"id":27,"name":"Venison - Striploin","description":"Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.","category_id":1,"image":"https://picsum.photos/161/162","price":57000,"content":"Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.","unit":"est"},
{"id":28,"name":"Spice - Paprika","description":"Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.","category_id":8,"image":"https://picsum.photos/494/495","price":36000,"content":"Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.","unit":"etiam"},
{"id":29,"name":"General Purpose Trigger","description":"Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.","category_id":5,"image":"https://picsum.photos/465/466","price":187000,"content":"Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.","unit":"interdum"},
{"id":30,"name":"V8 - Vegetable Cocktail","description":"Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.","category_id":7,"image":"https://picsum.photos/496/497","price":200000,"content":"In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.","unit":"massa"},
{"id":31,"name":"Shark - Loin","description":"Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.","category_id":8,"image":"https://picsum.photos/107/108","price":145000,"content":"Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.","unit":"tortor"},
{"id":32,"name":"Sprouts - Peppercress","description":"In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.","category_id":5,"image":"https://picsum.photos/200/201","price":160000,"content":"Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.","unit":"in"},
{"id":33,"name":"Jam - Apricot","description":"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.","category_id":2,"image":"https://picsum.photos/470/471","price":91000,"content":"Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.","unit":"duis"},
{"id":34,"name":"Beef - Diced","description":"Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.","category_id":9,"image":"https://picsum.photos/454/455","price":185000,"content":"Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.","unit":"dui"},
{"id":35,"name":"Sobe - Cranberry Grapefruit","description":"Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.","category_id":3,"image":"https://picsum.photos/285/286","price":145000,"content":"Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.","unit":"diam"},
{"id":36,"name":"Cheese - Woolwich Goat, Log","description":"Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.","category_id":5,"image":"https://picsum.photos/391/392","price":80000,"content":"Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.","unit":"justo"},
{"id":37,"name":"Truffle Cups - White Paper","description":"In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.","category_id":7,"image":"https://picsum.photos/209/210","price":161000,"content":"Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.","unit":"ligula"},
{"id":38,"name":"Cherries - Frozen","description":"Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.","category_id":5,"image":"https://picsum.photos/196/197","price":179000,"content":"Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.","unit":"dui"},
{"id":39,"name":"Broom - Corn","description":"Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.","category_id":3,"image":"https://picsum.photos/448/449","price":193000,"content":"Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.","unit":"aliquam"},
{"id":40,"name":"Beef - Kindney, Whole","description":"Sed ante. Vivamus tortor. Duis mattis egestas metus.","category_id":10,"image":"https://picsum.photos/215/216","price":28000,"content":"Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.","unit":"rutrum"},
{"id":41,"name":"Wine - Delicato Merlot","description":"In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.","category_id":11,"image":"https://picsum.photos/133/134","price":180000,"content":"Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.","unit":"justo"},
{"id":42,"name":"Cauliflower","description":"Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.","category_id":4,"image":"https://picsum.photos/416/417","price":17000,"content":"Phasellus in felis. Donec semper sapien a libero. Nam dui.","unit":"ac"},
{"id":43,"name":"Beef - Cow Feet Split","description":"Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.","category_id":4,"image":"https://picsum.photos/187/188","price":30000,"content":"Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.","unit":"posuere"},
{"id":44,"name":"Wine - Semi Dry Riesling Vineland","description":"Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.","category_id":10,"image":"https://picsum.photos/441/442","price":68000,"content":"Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.","unit":"eu"},
{"id":45,"name":"Salad Dressing","description":"Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.","category_id":9,"image":"https://picsum.photos/371/372","price":148000,"content":"Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.","unit":"eget"},
{"id":46,"name":"Nougat - Paste / Cream","description":"Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.","category_id":7,"image":"https://picsum.photos/219/220","price":15000,"content":"Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.","unit":"habitasse"},
{"id":47,"name":"Soup - French Onion","description":"Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.","category_id":4,"image":"https://picsum.photos/129/130","price":51000,"content":"Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.","unit":"viverra"},
{"id":48,"name":"Onions - Dried, Chopped","description":"Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.","category_id":11,"image":"https://picsum.photos/376/377","price":197000,"content":"Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.","unit":"posuere"},
{"id":49,"name":"Pepsi - 600ml","description":"Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.","category_id":5,"image":"https://picsum.photos/308/309","price":76000,"content":"Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.","unit":"aliquet"},
{"id":50,"name":"Seedlings - Clamshell","description":"Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.","category_id":6,"image":"https://picsum.photos/330/331","price":198000,"content":"Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.","unit":"magna"},
{"id":51,"name":"Cheese Cloth","description":"Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.","category_id":4,"image":"https://picsum.photos/460/461","price":105000,"content":"Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.","unit":"habitasse"},
{"id":52,"name":"Veal - Loin","description":"Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.","category_id":7,"image":"https://picsum.photos/389/390","price":146000,"content":"Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.","unit":"nunc"},
{"id":53,"name":"Turkey - Breast, Double","description":"Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.","category_id":5,"image":"https://picsum.photos/151/152","price":138000,"content":"In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.","unit":"primis"},
{"id":54,"name":"Chocolate - Dark Callets","description":"Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.","category_id":3,"image":"https://picsum.photos/458/459","price":142000,"content":"Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.","unit":"in"},
{"id":55,"name":"Crackers - Trio","description":"Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.","category_id":8,"image":"https://picsum.photos/453/454","price":154000,"content":"Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.","unit":"volutpat"},
{"id":56,"name":"Stock - Beef, White","description":"Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.","category_id":1,"image":"https://picsum.photos/392/393","price":54000,"content":"Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.","unit":"condimentum"},
{"id":57,"name":"Table Cloth - 53x69 Colour","description":"Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.","category_id":7,"image":"https://picsum.photos/493/494","price":175000,"content":"Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.","unit":"gravida"},
{"id":58,"name":"Tequila - Sauza Silver","description":"Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.","category_id":11,"image":"https://picsum.photos/335/336","price":76000,"content":"Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.","unit":"nulla"},
{"id":59,"name":"Soup - Campbells Beef Stew","description":"Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.","category_id":8,"image":"https://picsum.photos/259/260","price":52000,"content":"Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.","unit":"quis"},
{"id":60,"name":"Milk 2% 500 Ml","description":"Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.","category_id":4,"image":"https://picsum.photos/432/433","price":93000,"content":"Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.","unit":"primis"},
{"id":61,"name":"Hipnotiq Liquor","description":"Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.","category_id":1,"image":"https://picsum.photos/466/467","price":27000,"content":"Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.","unit":"sem"},
{"id":62,"name":"Flax Seed","description":"Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.","category_id":6,"image":"https://picsum.photos/457/458","price":145000,"content":"Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.","unit":"sapien"},
{"id":63,"name":"Potatoes - Instant, Mashed","description":"Fusce consequat. Nulla nisl. Nunc nisl.","category_id":9,"image":"https://picsum.photos/389/390","price":151000,"content":"Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.","unit":"convallis"},
{"id":64,"name":"Bay Leaf Fresh","description":"In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.","category_id":2,"image":"https://picsum.photos/442/443","price":173000,"content":"Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.","unit":"et"},
{"id":65,"name":"Pepper - Chili Powder","description":"Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.","category_id":3,"image":"https://picsum.photos/299/300","price":166000,"content":"Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.","unit":"pretium"},
{"id":66,"name":"Gatorade - Fruit Punch","description":"Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.","category_id":2,"image":"https://picsum.photos/267/268","price":17000,"content":"Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.","unit":"habitasse"},
{"id":67,"name":"Beef - Striploin","description":"Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.","category_id":5,"image":"https://picsum.photos/300/301","price":125000,"content":"In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.","unit":"morbi"},
{"id":68,"name":"Lighter - Bbq","description":"Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.","category_id":6,"image":"https://picsum.photos/211/212","price":77000,"content":"Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.","unit":"tempor"},
{"id":69,"name":"Raspberries - Frozen","description":"Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.","category_id":6,"image":"https://picsum.photos/399/400","price":36000,"content":"Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.","unit":"molestie"},
{"id":70,"name":"Fiddlehead - Frozen","description":"In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.","category_id":6,"image":"https://picsum.photos/254/255","price":93000,"content":"Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.","unit":"vestibulum"},
{"id":71,"name":"Kolrabi","description":"In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.","category_id":8,"image":"https://picsum.photos/423/424","price":43000,"content":"Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.","unit":"a"},
{"id":72,"name":"Garbag Bags - Black","description":"Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.","category_id":2,"image":"https://picsum.photos/169/170","price":191000,"content":"Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.","unit":"id"},
{"id":73,"name":"Red Currant Jelly","description":"Sed ante. Vivamus tortor. Duis mattis egestas metus.","category_id":3,"image":"https://picsum.photos/230/231","price":173000,"content":"Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.","unit":"dis"},
{"id":74,"name":"Cardamon Seed / Pod","description":"Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.","category_id":1,"image":"https://picsum.photos/224/225","price":170000,"content":"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.","unit":"egestas"},
{"id":75,"name":"Soup Bowl Clear 8oz92008","description":"Sed ante. Vivamus tortor. Duis mattis egestas metus.","category_id":5,"image":"https://picsum.photos/186/187","price":124000,"content":"Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.","unit":"purus"},
{"id":76,"name":"Wine - Pinot Grigio Collavini","description":"Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.","category_id":10,"image":"https://picsum.photos/330/331","price":198000,"content":"Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.","unit":"sapien"},
{"id":77,"name":"Muffin Batt - Ban Dream Zero","description":"Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.","category_id":2,"image":"https://picsum.photos/241/242","price":95000,"content":"Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.","unit":"odio"},
{"id":78,"name":"Corn Meal","description":"Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.","category_id":6,"image":"https://picsum.photos/167/168","price":42000,"content":"Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.","unit":"ipsum"},
{"id":79,"name":"Bread - Bagels, Mini","description":"Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.","category_id":1,"image":"https://picsum.photos/192/193","price":179000,"content":"Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.","unit":"pede"},
{"id":80,"name":"Sultanas","description":"Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.","category_id":9,"image":"https://picsum.photos/122/123","price":139000,"content":"Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.","unit":"consequat"},
{"id":81,"name":"Buffalo - Striploin","description":"Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.","category_id":10,"image":"https://picsum.photos/404/405","price":198000,"content":"Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.","unit":"nisl"},
{"id":82,"name":"Split Peas - Green, Dry","description":"Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.","category_id":1,"image":"https://picsum.photos/441/442","price":42000,"content":"Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.","unit":"ut"},
{"id":83,"name":"Cookies Oatmeal Raisin","description":"In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.","category_id":8,"image":"https://picsum.photos/123/124","price":69000,"content":"Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.","unit":"nulla"},
{"id":84,"name":"Thyme - Fresh","description":"Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.","category_id":3,"image":"https://picsum.photos/154/155","price":112000,"content":"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.","unit":"sapien"},
{"id":85,"name":"Garlic - Peeled","description":"Sed ante. Vivamus tortor. Duis mattis egestas metus.","category_id":3,"image":"https://picsum.photos/373/374","price":42000,"content":"Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.","unit":"nisi"},
{"id":86,"name":"Island Oasis - Ice Cream Mix","description":"Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.","category_id":10,"image":"https://picsum.photos/338/339","price":17000,"content":"Phasellus in felis. Donec semper sapien a libero. Nam dui.","unit":"molestie"},
{"id":87,"name":"Flour - Bread","description":"Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.","category_id":7,"image":"https://picsum.photos/164/165","price":175000,"content":"Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.","unit":"id"},
{"id":88,"name":"Guava","description":"Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.","category_id":2,"image":"https://picsum.photos/319/320","price":167000,"content":"Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.","unit":"magna"},
{"id":89,"name":"Jam - Blackberry, 20 Ml Jar","description":"Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.","category_id":8,"image":"https://picsum.photos/280/281","price":190000,"content":"Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.","unit":"lorem"},
{"id":90,"name":"Grapes - Red","description":"In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.","category_id":5,"image":"https://picsum.photos/420/421","price":168000,"content":"Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.","unit":"ut"},
{"id":91,"name":"Sultanas","description":"Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.","category_id":10,"image":"https://picsum.photos/465/466","price":138000,"content":"Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.","unit":"id"},
{"id":92,"name":"Bread - Hamburger Buns","description":"Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.","category_id":6,"image":"https://picsum.photos/251/252","price":124000,"content":"Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.","unit":"nascetur"},
{"id":93,"name":"Ranchero - Primerba, Paste","description":"Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.","category_id":7,"image":"https://picsum.photos/218/219","price":53000,"content":"Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.","unit":"imperdiet"},
{"id":94,"name":"Garam Marsala","description":"Sed ante. Vivamus tortor. Duis mattis egestas metus.","category_id":3,"image":"https://picsum.photos/429/430","price":57000,"content":"Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.","unit":"natoque"},
{"id":95,"name":"Coffee - Cafe Moreno","description":"In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.","category_id":7,"image":"https://picsum.photos/285/286","price":78000,"content":"Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.","unit":"odio"},
{"id":96,"name":"Salmon - Atlantic, Skin On","description":"Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.","category_id":3,"image":"https://picsum.photos/353/354","price":32000,"content":"In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.","unit":"phasellus"},
{"id":97,"name":"Lamb - Leg, Boneless","description":"Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.","category_id":2,"image":"https://picsum.photos/193/194","price":61000,"content":"Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.","unit":"vel"},
{"id":98,"name":"Bread - Pumpernickle, Rounds","description":"Sed ante. Vivamus tortor. Duis mattis egestas metus.","category_id":9,"image":"https://picsum.photos/387/388","price":183000,"content":"Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.","unit":"mauris"},
{"id":99,"name":"Eggs - Extra Large","description":"In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.","category_id":2,"image":"https://picsum.photos/180/181","price":171000,"content":"In congue. Etiam justo. Etiam pretium iaculis justo.","unit":"at"},
{"id":100,"name":"Lettuce - Mini Greens, Whole","description":"In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.","category_id":4,"image":"https://picsum.photos/177/178","price":53000,"content":"Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.","unit":"pellentesque"}]`
);

export const listVariants = JSON.parse(`
[{"id":1,"name":"L","productId":42,"stock":25,"price":55000,"costPrice":47000},
{"id":2,"name":"S","productId":50,"stock":61,"price":83000,"costPrice":20000},
{"id":3,"name":"2XL","productId":61,"stock":11,"price":52000,"costPrice":28000},
{"id":4,"name":"2XL","productId":81,"stock":60,"price":98000,"costPrice":34000},
{"id":5,"name":"3XL","productId":40,"stock":30,"price":73000,"costPrice":25000},
{"id":6,"name":"2XL","productId":88,"stock":7,"price":89000,"costPrice":40000},
{"id":7,"name":"M","productId":70,"stock":44,"price":100000,"costPrice":12000},
{"id":8,"name":"M","productId":26,"stock":49,"price":66000,"costPrice":39000},
{"id":9,"name":"2XL","productId":14,"stock":35,"price":99000,"costPrice":26000},
{"id":10,"name":"L","productId":66,"stock":40,"price":93000,"costPrice":40000},
{"id":11,"name":"M","productId":54,"stock":18,"price":89000,"costPrice":11000},
{"id":12,"name":"M","productId":32,"stock":22,"price":86000,"costPrice":36000},
{"id":13,"name":"M","productId":100,"stock":4,"price":86000,"costPrice":30000},
{"id":14,"name":"XL","productId":3,"stock":8,"price":63000,"costPrice":40000},
{"id":15,"name":"S","productId":88,"stock":44,"price":87000,"costPrice":41000},
{"id":16,"name":"S","productId":78,"stock":14,"price":99000,"costPrice":48000},
{"id":17,"name":"XS","productId":58,"stock":12,"price":84000,"costPrice":40000},
{"id":18,"name":"L","productId":11,"stock":49,"price":99000,"costPrice":17000},
{"id":19,"name":"M","productId":93,"stock":47,"price":71000,"costPrice":24000},
{"id":20,"name":"2XL","productId":13,"stock":97,"price":81000,"costPrice":12000},
{"id":21,"name":"XS","productId":54,"stock":49,"price":82000,"costPrice":47000},
{"id":22,"name":"2XL","productId":72,"stock":70,"price":68000,"costPrice":27000},
{"id":23,"name":"3XL","productId":54,"stock":78,"price":91000,"costPrice":22000},
{"id":24,"name":"3XL","productId":82,"stock":75,"price":93000,"costPrice":50000},
{"id":25,"name":"L","productId":41,"stock":77,"price":63000,"costPrice":22000},
{"id":26,"name":"S","productId":88,"stock":65,"price":87000,"costPrice":19000},
{"id":27,"name":"3XL","productId":73,"stock":76,"price":51000,"costPrice":16000},
{"id":28,"name":"S","productId":39,"stock":69,"price":78000,"costPrice":41000},
{"id":29,"name":"XS","productId":90,"stock":57,"price":90000,"costPrice":47000},
{"id":30,"name":"L","productId":49,"stock":65,"price":86000,"costPrice":20000},
{"id":31,"name":"XL","productId":69,"stock":60,"price":80000,"costPrice":43000},
{"id":32,"name":"L","productId":92,"stock":52,"price":84000,"costPrice":16000},
{"id":33,"name":"XS","productId":43,"stock":14,"price":85000,"costPrice":39000},
{"id":34,"name":"S","productId":80,"stock":64,"price":55000,"costPrice":41000},
{"id":35,"name":"XS","productId":19,"stock":49,"price":69000,"costPrice":15000},
{"id":36,"name":"M","productId":35,"stock":13,"price":95000,"costPrice":27000},
{"id":37,"name":"3XL","productId":90,"stock":60,"price":74000,"costPrice":26000},
{"id":38,"name":"M","productId":86,"stock":100,"price":69000,"costPrice":26000},
{"id":39,"name":"M","productId":83,"stock":38,"price":98000,"costPrice":29000},
{"id":40,"name":"2XL","productId":82,"stock":79,"price":95000,"costPrice":36000},
{"id":41,"name":"3XL","productId":80,"stock":71,"price":55000,"costPrice":20000},
{"id":42,"name":"2XL","productId":91,"stock":16,"price":86000,"costPrice":19000},
{"id":43,"name":"L","productId":100,"stock":100,"price":80000,"costPrice":49000},
{"id":44,"name":"L","productId":84,"stock":2,"price":52000,"costPrice":14000},
{"id":45,"name":"XL","productId":99,"stock":33,"price":89000,"costPrice":19000},
{"id":46,"name":"M","productId":43,"stock":100,"price":73000,"costPrice":41000},
{"id":47,"name":"3XL","productId":99,"stock":51,"price":86000,"costPrice":32000},
{"id":48,"name":"XL","productId":85,"stock":14,"price":97000,"costPrice":46000},
{"id":49,"name":"M","productId":52,"stock":83,"price":53000,"costPrice":44000},
{"id":50,"name":"3XL","productId":68,"stock":52,"price":54000,"costPrice":41000},
{"id":51,"name":"XS","productId":80,"stock":98,"price":67000,"costPrice":24000},
{"id":52,"name":"2XL","productId":70,"stock":28,"price":68000,"costPrice":45000},
{"id":53,"name":"M","productId":21,"stock":61,"price":54000,"costPrice":29000},
{"id":54,"name":"3XL","productId":92,"stock":86,"price":96000,"costPrice":14000},
{"id":55,"name":"XL","productId":41,"stock":3,"price":70000,"costPrice":35000},
{"id":56,"name":"M","productId":4,"stock":41,"price":82000,"costPrice":31000},
{"id":57,"name":"XL","productId":23,"stock":30,"price":94000,"costPrice":47000},
{"id":58,"name":"M","productId":85,"stock":56,"price":70000,"costPrice":32000},
{"id":59,"name":"S","productId":34,"stock":100,"price":84000,"costPrice":50000},
{"id":60,"name":"XL","productId":5,"stock":36,"price":66000,"costPrice":22000},
{"id":61,"name":"3XL","productId":18,"stock":99,"price":66000,"costPrice":16000},
{"id":62,"name":"XL","productId":38,"stock":70,"price":92000,"costPrice":25000},
{"id":63,"name":"XL","productId":65,"stock":73,"price":86000,"costPrice":31000},
{"id":64,"name":"XL","productId":67,"stock":48,"price":75000,"costPrice":14000},
{"id":65,"name":"XS","productId":88,"stock":97,"price":59000,"costPrice":12000},
{"id":66,"name":"2XL","productId":59,"stock":68,"price":82000,"costPrice":32000},
{"id":67,"name":"S","productId":29,"stock":51,"price":86000,"costPrice":43000},
{"id":68,"name":"XS","productId":93,"stock":69,"price":94000,"costPrice":37000},
{"id":69,"name":"M","productId":16,"stock":10,"price":66000,"costPrice":17000},
{"id":70,"name":"S","productId":30,"stock":42,"price":63000,"costPrice":21000},
{"id":71,"name":"XL","productId":30,"stock":42,"price":71000,"costPrice":17000},
{"id":72,"name":"L","productId":59,"stock":11,"price":85000,"costPrice":49000},
{"id":73,"name":"XS","productId":28,"stock":12,"price":90000,"costPrice":11000},
{"id":74,"name":"S","productId":59,"stock":91,"price":82000,"costPrice":16000},
{"id":75,"name":"2XL","productId":58,"stock":20,"price":95000,"costPrice":12000},
{"id":76,"name":"M","productId":65,"stock":79,"price":60000,"costPrice":18000},
{"id":77,"name":"L","productId":30,"stock":6,"price":68000,"costPrice":19000},
{"id":78,"name":"M","productId":28,"stock":15,"price":95000,"costPrice":20000},
{"id":79,"name":"M","productId":92,"stock":58,"price":64000,"costPrice":45000},
{"id":80,"name":"3XL","productId":22,"stock":88,"price":97000,"costPrice":22000},
{"id":81,"name":"XS","productId":49,"stock":92,"price":84000,"costPrice":50000},
{"id":82,"name":"XL","productId":45,"stock":13,"price":63000,"costPrice":45000},
{"id":83,"name":"L","productId":64,"stock":43,"price":92000,"costPrice":21000},
{"id":84,"name":"S","productId":94,"stock":67,"price":90000,"costPrice":27000},
{"id":85,"name":"M","productId":12,"stock":94,"price":58000,"costPrice":28000},
{"id":86,"name":"XS","productId":3,"stock":4,"price":87000,"costPrice":14000},
{"id":87,"name":"XL","productId":53,"stock":1,"price":69000,"costPrice":35000},
{"id":88,"name":"L","productId":24,"stock":91,"price":56000,"costPrice":39000},
{"id":89,"name":"2XL","productId":38,"stock":66,"price":78000,"costPrice":31000},
{"id":90,"name":"L","productId":27,"stock":93,"price":69000,"costPrice":12000},
{"id":91,"name":"L","productId":83,"stock":10,"price":61000,"costPrice":19000},
{"id":92,"name":"XS","productId":90,"stock":53,"price":81000,"costPrice":48000},
{"id":93,"name":"S","productId":38,"stock":19,"price":59000,"costPrice":24000},
{"id":94,"name":"M","productId":62,"stock":34,"price":99000,"costPrice":10000},
{"id":95,"name":"2XL","productId":90,"stock":30,"price":83000,"costPrice":23000},
{"id":96,"name":"L","productId":89,"stock":25,"price":62000,"costPrice":32000},
{"id":97,"name":"XS","productId":13,"stock":61,"price":69000,"costPrice":18000},
{"id":98,"name":"XS","productId":5,"stock":47,"price":54000,"costPrice":50000},
{"id":99,"name":"M","productId":79,"stock":97,"price":75000,"costPrice":28000},
{"id":100,"name":"3XL","productId":69,"stock":36,"price":92000,"costPrice":49000},
{"id":101,"name":"M","productId":19,"stock":91,"price":66000,"costPrice":31000},
{"id":102,"name":"M","productId":43,"stock":18,"price":63000,"costPrice":26000},
{"id":103,"name":"3XL","productId":63,"stock":76,"price":80000,"costPrice":33000},
{"id":104,"name":"S","productId":31,"stock":41,"price":75000,"costPrice":41000},
{"id":105,"name":"M","productId":51,"stock":87,"price":76000,"costPrice":30000},
{"id":106,"name":"XL","productId":100,"stock":36,"price":79000,"costPrice":18000},
{"id":107,"name":"M","productId":67,"stock":80,"price":56000,"costPrice":45000},
{"id":108,"name":"S","productId":91,"stock":49,"price":93000,"costPrice":42000},
{"id":109,"name":"2XL","productId":42,"stock":90,"price":98000,"costPrice":20000},
{"id":110,"name":"L","productId":70,"stock":27,"price":99000,"costPrice":34000},
{"id":111,"name":"S","productId":7,"stock":44,"price":52000,"costPrice":24000},
{"id":112,"name":"M","productId":78,"stock":15,"price":70000,"costPrice":11000},
{"id":113,"name":"XS","productId":10,"stock":18,"price":62000,"costPrice":20000},
{"id":114,"name":"L","productId":77,"stock":57,"price":81000,"costPrice":21000},
{"id":115,"name":"3XL","productId":2,"stock":68,"price":57000,"costPrice":44000},
{"id":116,"name":"S","productId":85,"stock":53,"price":53000,"costPrice":42000},
{"id":117,"name":"S","productId":59,"stock":27,"price":93000,"costPrice":14000},
{"id":118,"name":"XL","productId":56,"stock":47,"price":92000,"costPrice":37000},
{"id":119,"name":"L","productId":84,"stock":93,"price":58000,"costPrice":48000},
{"id":120,"name":"M","productId":37,"stock":66,"price":70000,"costPrice":21000},
{"id":121,"name":"XS","productId":63,"stock":67,"price":60000,"costPrice":17000},
{"id":122,"name":"M","productId":56,"stock":40,"price":89000,"costPrice":47000},
{"id":123,"name":"S","productId":91,"stock":49,"price":79000,"costPrice":13000},
{"id":124,"name":"L","productId":82,"stock":46,"price":85000,"costPrice":37000},
{"id":125,"name":"S","productId":32,"stock":84,"price":97000,"costPrice":10000},
{"id":126,"name":"L","productId":23,"stock":35,"price":84000,"costPrice":20000},
{"id":127,"name":"M","productId":78,"stock":27,"price":77000,"costPrice":39000},
{"id":128,"name":"XS","productId":69,"stock":80,"price":65000,"costPrice":17000},
{"id":129,"name":"M","productId":79,"stock":94,"price":81000,"costPrice":44000},
{"id":130,"name":"M","productId":3,"stock":54,"price":61000,"costPrice":50000},
{"id":131,"name":"M","productId":100,"stock":58,"price":72000,"costPrice":30000},
{"id":132,"name":"2XL","productId":16,"stock":91,"price":81000,"costPrice":10000},
{"id":133,"name":"2XL","productId":39,"stock":30,"price":50000,"costPrice":49000},
{"id":134,"name":"M","productId":13,"stock":52,"price":93000,"costPrice":23000},
{"id":135,"name":"S","productId":71,"stock":2,"price":59000,"costPrice":12000},
{"id":136,"name":"XS","productId":71,"stock":1,"price":86000,"costPrice":41000},
{"id":137,"name":"XL","productId":92,"stock":100,"price":67000,"costPrice":36000},
{"id":138,"name":"M","productId":3,"stock":2,"price":57000,"costPrice":37000},
{"id":139,"name":"L","productId":36,"stock":84,"price":76000,"costPrice":25000},
{"id":140,"name":"L","productId":28,"stock":98,"price":57000,"costPrice":27000},
{"id":141,"name":"M","productId":56,"stock":77,"price":63000,"costPrice":41000},
{"id":142,"name":"L","productId":56,"stock":37,"price":60000,"costPrice":37000},
{"id":143,"name":"M","productId":87,"stock":95,"price":95000,"costPrice":45000},
{"id":144,"name":"XS","productId":71,"stock":90,"price":81000,"costPrice":16000},
{"id":145,"name":"L","productId":19,"stock":80,"price":57000,"costPrice":34000},
{"id":146,"name":"S","productId":16,"stock":50,"price":52000,"costPrice":47000},
{"id":147,"name":"S","productId":99,"stock":2,"price":71000,"costPrice":30000},
{"id":148,"name":"L","productId":63,"stock":20,"price":95000,"costPrice":24000},
{"id":149,"name":"L","productId":63,"stock":51,"price":91000,"costPrice":38000},
{"id":150,"name":"2XL","productId":7,"stock":58,"price":71000,"costPrice":47000},
{"id":151,"name":"M","productId":93,"stock":26,"price":67000,"costPrice":13000},
{"id":152,"name":"M","productId":24,"stock":34,"price":73000,"costPrice":28000},
{"id":153,"name":"XS","productId":11,"stock":72,"price":89000,"costPrice":15000},
{"id":154,"name":"2XL","productId":83,"stock":40,"price":99000,"costPrice":10000},
{"id":155,"name":"S","productId":10,"stock":97,"price":87000,"costPrice":22000},
{"id":156,"name":"2XL","productId":3,"stock":10,"price":89000,"costPrice":28000},
{"id":157,"name":"3XL","productId":75,"stock":47,"price":60000,"costPrice":45000},
{"id":158,"name":"XL","productId":34,"stock":18,"price":86000,"costPrice":10000},
{"id":159,"name":"L","productId":86,"stock":99,"price":90000,"costPrice":37000},
{"id":160,"name":"3XL","productId":54,"stock":31,"price":65000,"costPrice":48000},
{"id":161,"name":"XL","productId":94,"stock":95,"price":91000,"costPrice":29000},
{"id":162,"name":"L","productId":78,"stock":81,"price":89000,"costPrice":20000},
{"id":163,"name":"XS","productId":96,"stock":77,"price":71000,"costPrice":40000},
{"id":164,"name":"3XL","productId":32,"stock":48,"price":52000,"costPrice":47000},
{"id":165,"name":"XL","productId":60,"stock":100,"price":79000,"costPrice":40000},
{"id":166,"name":"XL","productId":73,"stock":17,"price":62000,"costPrice":25000},
{"id":167,"name":"XS","productId":62,"stock":81,"price":55000,"costPrice":32000},
{"id":168,"name":"M","productId":40,"stock":92,"price":55000,"costPrice":44000},
{"id":169,"name":"M","productId":77,"stock":30,"price":63000,"costPrice":13000},
{"id":170,"name":"XL","productId":75,"stock":21,"price":100000,"costPrice":11000},
{"id":171,"name":"3XL","productId":79,"stock":15,"price":71000,"costPrice":18000},
{"id":172,"name":"3XL","productId":5,"stock":61,"price":77000,"costPrice":15000},
{"id":173,"name":"S","productId":65,"stock":72,"price":53000,"costPrice":15000},
{"id":174,"name":"S","productId":36,"stock":71,"price":81000,"costPrice":32000},
{"id":175,"name":"M","productId":100,"stock":11,"price":61000,"costPrice":40000},
{"id":176,"name":"2XL","productId":14,"stock":6,"price":69000,"costPrice":37000},
{"id":177,"name":"M","productId":61,"stock":98,"price":80000,"costPrice":20000},
{"id":178,"name":"XS","productId":49,"stock":75,"price":86000,"costPrice":41000},
{"id":179,"name":"XS","productId":51,"stock":43,"price":97000,"costPrice":35000},
{"id":180,"name":"XL","productId":18,"stock":22,"price":62000,"costPrice":30000},
{"id":181,"name":"XL","productId":66,"stock":60,"price":68000,"costPrice":31000},
{"id":182,"name":"2XL","productId":23,"stock":83,"price":83000,"costPrice":19000},
{"id":183,"name":"2XL","productId":43,"stock":50,"price":72000,"costPrice":21000},
{"id":184,"name":"XL","productId":75,"stock":63,"price":56000,"costPrice":36000},
{"id":185,"name":"3XL","productId":56,"stock":35,"price":100000,"costPrice":11000},
{"id":186,"name":"S","productId":26,"stock":56,"price":89000,"costPrice":34000},
{"id":187,"name":"3XL","productId":5,"stock":11,"price":67000,"costPrice":42000},
{"id":188,"name":"M","productId":98,"stock":46,"price":86000,"costPrice":38000},
{"id":189,"name":"XS","productId":55,"stock":65,"price":86000,"costPrice":17000},
{"id":190,"name":"XL","productId":73,"stock":3,"price":96000,"costPrice":34000},
{"id":191,"name":"XL","productId":12,"stock":44,"price":77000,"costPrice":46000},
{"id":192,"name":"M","productId":23,"stock":43,"price":52000,"costPrice":29000},
{"id":193,"name":"XS","productId":4,"stock":20,"price":98000,"costPrice":50000},
{"id":194,"name":"XL","productId":38,"stock":55,"price":78000,"costPrice":13000},
{"id":195,"name":"2XL","productId":22,"stock":17,"price":89000,"costPrice":43000},
{"id":196,"name":"2XL","productId":9,"stock":96,"price":53000,"costPrice":35000},
{"id":197,"name":"XS","productId":98,"stock":8,"price":84000,"costPrice":45000},
{"id":198,"name":"XS","productId":75,"stock":60,"price":83000,"costPrice":31000},
{"id":199,"name":"XL","productId":42,"stock":71,"price":60000,"costPrice":25000},
{"id":200,"name":"XS","productId":79,"stock":3,"price":52000,"costPrice":47000}]
`);

export const listShippingMethods = JSON.parse(`
[{
  "id": 1,
  "name": "Reatta",
  "description": "Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis."
}, {
  "id": 2,
  "name": "MX-5",
  "description": "Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl."
}, {
  "id": 3,
  "name": "Ion",
  "description": "Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem."
}, {
  "id": 4,
  "name": "Alcyone SVX",
  "description": "Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros."
}, {
  "id": 5,
  "name": "MR2",
  "description": "Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi."
}, {
  "id": 6,
  "name": "CL-Class",
  "description": "Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris."
}, {
  "id": 7,
  "name": "RS4",
  "description": "Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus."
}, {
  "id": 8,
  "name": "MKZ",
  "description": "Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est."
}, {
  "id": 9,
  "name": "Transit Connect",
  "description": "Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit."
}, {
  "id": 10,
  "name": "Rodeo Sport",
  "description": "Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh."
}]
`);

export const listCardTypes = JSON.parse(`
[{
  "id": 1,
  "name": "visa",
  "fee": 0.13
}, {
  "id": 2,
  "name": "mastercard",
  "fee": 0.77
}, {
  "id": 3,
  "name": "visa",
  "fee": 0.23
}, {
  "id": 4,
  "name": "americanexpress",
  "fee": 0.73
}, {
  "id": 5,
  "name": "americanexpress",
  "fee": 0.7
}, {
  "id": 6,
  "name": "visa",
  "fee": 0.2
}, {
  "id": 7,
  "name": "americanexpress",
  "fee": 0.17
}, {
  "id": 8,
  "name": "visa",
  "fee": 0.33
}, {
  "id": 9,
  "name": "americanexpress",
  "fee": 0.93
}, {
  "id": 10,
  "name": "americanexpress",
  "fee": 0.08
}]
`);
